export const FREE_SHIPPING_THRESHOLD = 40;
export const FREE_SHIPPING_THRESHOLD_EURO = `€${FREE_SHIPPING_THRESHOLD}`;
export const FREE_SHIPPING_THRESHOLD_TEXT = `${FREE_SHIPPING_THRESHOLD} €`;
export const FREE_SHIPPING_COPY = `Nemokamas pristatymas nuo ${FREE_SHIPPING_THRESHOLD_EURO}`;

export const NEWSLETTER_DISCOUNT_PERCENT = 10;
export const NEWSLETTER_DISCOUNT_CODE = process.env.NEWSLETTER_DISCOUNT_CODE || 'LABAS10';
